Feature/combine node with rest
wiet-industries/notarial-blockchain pull request #13
Opened 2021-12-13 19:53 UTC by adrianryt

2021-12-15 10:23 UTC, Atheam requested changes

2021-12-15 10:23 UTC, Atheam commented on src/main/java/rest/NodeController.java
> +        response.addProperty("message", "OK");
I think we should respond to user with node ID in this method. Either by waiting or pushing notification after some time.

2021-12-15 10:23 UTC, Atheam commented on src/main/java/rest/NodeController.java
> +    public String registerHandler() {
We should first check if node is connected and has ID assigned, also ID should be sent to user in /connect handler not here.

2021-12-15 10:23 UTC, Atheam commented on src/main/java/rest/NodeController.java
> +    public String broadcastHandler() {
Check if node is connected and registered

2021-12-15 10:23 UTC, Atheam commented on src/main/java/node/Node.java
> +    public void addTransactionToMemPool(Transaction transaction) {
I think we should move this to some BlockchainHandler class to keep Node class functionality restricted to processing Messeges, same as we did with ServerSessionHandler and PeerConnectionHandler

2021-12-15 10:23 UTC, Atheam commented on src/main/java/node/Node.java
> +    private void handleBlockchainFromOtherNode(List<Block> blockchain) {
Same as above, move to another class

2021-12-15 10:23 UTC, Atheam commented on src/main/java/node/Listeners/UdpListener.java
> +            System.out.println(new String(Arrays.copyOf(datagram.getData(), datagram.getLength())));
Move trimming bytes array to seperate metod.

2021-12-15 10:23 UTC, Atheam commented on src/main/java/blockchain/Blockchain.java
> +    private EventListener listener;
Make it a list of EventListeners (even if now we use only one listener) and also change subscribe and notify to handle a list of listeners. Also consider moving this event managing functionality to abstract class (look TcpListener or UdpListener).

2021-12-15 10:26 UTC, adrianryt commented on src/main/java/rest/NodeController.java
> +        response.addProperty("message", "OK");
It is in TODO list

2021-12-15 10:26 UTC, adrianryt commented on src/main/java/rest/NodeController.java
> +    public String registerHandler() {
It is in TODO list

2021-12-15 10:26 UTC, adrianryt commented on src/main/java/rest/NodeController.java
> +    public String broadcastHandler() {
It is in TODO list

2021-12-15 10:28 UTC, adrianryt commented on src/main/java/node/Listeners/UdpListener.java
> +            System.out.println(new String(Arrays.copyOf(datagram.getData(), datagram.getLength())));
You did this 😄

2021-12-15 10:28 UTC, adrianryt commented on src/main/java/blockchain/Blockchain.java
> +    private EventListener listener;
read TODO

2021-12-15 10:31 UTC, Atheam commented on src/main/java/node/Listeners/UdpListener.java
> +            System.out.println(new String(Arrays.copyOf(datagram.getData(), datagram.getLength())));
?

2021-12-15 10:34 UTC, Atheam commented on src/main/java/blockchain/Blockchain.java
> +    private EventListener listener;
i think its straight forward you can just change it no need to postpone it.

2022-01-05 18:54 UTC, Atheam approved these changes

2022-01-05 18:54 UTC, wawel37 approved these changes

2022-01-05 18:54 UTC, merged